config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"


  ## Root Route ##
  root 'pages#home'
  ## ROUTES ##
  get 'about', to: 'pages#about'

  resources :articles

  # User Routes
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  # Login Routes
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Category Routes
  resources :categories, except: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord

    # Associations
    belongs_to :user

    # Validation on title
    validates :title, presence: true, length: {minimum: 3, maximum: 50}

    # Validation on description
    validates :description, presence: true, length: { minimum: 10, maximum: 300}

    # Validation on presence of user_id
    validates :user_id, presence: true


end

app/models/category.rb
class Category < ApplicationRecord

    # validations
    validates :name, presence: true, length: {minimum:3, maximum:25}
    validates_uniqueness_of :name

end

app/models/user.rb
class User < ApplicationRecord 

    # Associations
    has_many :articles, dependent: :destroy

    # Downcase email
    before_save { self.email = email.downcase }

    # Validations on Username
    validates :username, presence: true, uniqueness: { case_sensitive: false}, length: {minimum:3, maximum: 25}

    # Validations on Email
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

    validates :email, presence: true, uniqueness: {case_sensitive: false}, length: {maximum: 105},
    format: {with: VALID_EMAIL_REGEX}

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        # return current_user if exists, else retrieve it with its session
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        # return true or false
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:danger] = "You mist be logged in to perform that action"
            redirect_to root_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # call set_article method before selected Methods
  before_action :set_article, only: [:edit, :update,:show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        # @articles = Article.all
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end

    def new
        @article = Article.new
    end

    def edit 
        # @article = Article.find(params[:id])
    end


    def create 
        # To debug
        # debugger
        @article = Article.new(article_params)
        # hardcode user id now for test
        @article.user = current_user
        if @article.save
            flash[:success] = 'Article is Successfully Created'
            redirect_to article_path(@article)
        else 
            render 'new'
        end
    end

    def update

        # @article = Article.find(params[:id])
        if @article.update(article_params)
            flash[:success] = 'Article is Updated Successfully'
            redirect_to article_path(@article)
        else 
            render 'edit'
        end
    end


    def show 
        # @article = Article.find(params[:id])
    end

    def destroy
        # @article = Article.find(params[:id])
        @article.destroy
        flash[:danger] = "Article has been Deleted Successfully"
        redirect_to articles_path
    end


    private
    def set_article
        @article = Article.find(params[:id])
    end
    def article_params
        params.require(:article).permit(:title, :description)
    end

    def require_same_user
        if current_user != @article.user and !current_user.admin?
            flash[:danger] = "You can only edit or delete your own articles"
            redirect_to root_path
        end

    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController 

    before_action :require_admin, except: [:index, :show]


    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end

    def new 
        @category = Category.new
    end

    def create 
        @category = Category.new(category_params)
        if @category.save 
            flash[:success] = "Category was created successfully"
            redirect_to categories_path
        else 
            render 'new'
        end

    end

    def show 

    end


    private 
    def category_params 
        params.require(:category).permit(:name)
    end


    def require_admin 
        if !logged_in? || (logged_in? and !current_user.admin?)
            flash[:danger] ="Only admin can perform that action"
            redirect_to categories_path 
        end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
        # go to article listing if logged in
        redirect_to articles_path if logged_in?
    end


    def about 
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 

    def new
    end

    def create 
        # find email
        user = User.find_by(email: params[:session][:email].downcase)
        # check if valid and compare password
        if user && user.authenticate(params[:session][:password])
            # setting session in browser
            session[:user_id] = user.id 
            flash[:success] = "You have Successfully Logged in"
            redirect_to user_path(user)
        else
            flash.now[:danger] = "Invalid Credentials"
            render 'new'
        end

    end

    def destroy 
        # setting session to nill
        session[:user_id] = nil
        flash[:success] = "You have successfully Logged out"
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController 

    # call set_user before edit,update, show actions
    before_action :set_user, only: [:edit, :update, :show]
    before_action :require_same_user, only: [:edit, :update]
    before_action :require_admin, only: [:destroy]
    def index
        @users = User.order('created_at DESC').paginate(page: params[:page], per_page: 2)
    end

    def new 
        @user = User.new
    end

    def show 
        # @user = User.find(params[:id])
        @user_articles = @user.articles.paginate(page: params[:page], per_page: 2)
    end

    def destroy 
        @user = User.find(params[:id])
        if @user.destroy 
            flash[:danger] = "User and all articles created by user have been deleted"
            redirect_to users_path
        end
    end
    
    def create 
        @user = User.new(users_params)
        if @user.save 
            session[:user_id] = @user.id
            flash[:success] = "Welcome to alpha blog #{@user.username}"
            redirect_to user_path(@user)
        else
            render 'new'
        end
    end

    def edit 
        # @user = User.find(params[:id])
    end

    def update 
        # @user = User.find(params[:id])
        if @user.update(users_params)
            flash[:success] = "Your account was updated Successfully"
            redirect_to articles_path
        else
            render 'edit'
        end
    end


    private
    def users_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        @user = User.find(params[:id])
    end

    def require_same_user
        if current_user != @user and !current_user.admin?
            flash[:dangers] = "You can only edit your own account"
            redirect_to root_path
        end
    end

    def require_admin
        # check if admin
        if logged_in? and !current_user.admin? 
            flash[:danger] = "only admin user can perform that action"
            redirect_to root_path
        end
    end



end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = {size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "img-circle")
    end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
<div class="row">
    <div class="col-xs-8 col-xs-offset-2 py-4">
        <div class="card p-2 border-0 bg-card">
            <div class="card-body">
                <div class="article-title">
                    <%= link_to article.title, article_path(article) %>
                </div>
                <div class="article-body">   
                    <%= truncate(article.description, length: 100) %>
                    <%= article.user.username if article.user %>
                    <%= time_ago_in_words(article.created_at)  %> ago
                    <%= time_ago_in_words(article.updated_at)  %> ago
                </div>
                <div class="article-actions">
                    <% if logged_in? && (current_user == article.user || current_user.admin?) %>
                    <%= link_to "Edit Article", edit_article_path(article), class: "btn btn-sm btn-primary" %> 

                    <%= button_to "Delete Article", article_path(article), method: :delete, data: {confirm: "are you sure you want to delete the article?"}, class: "btn btn-sm btn-danger"  %>

                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>
<% end %> 

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row ">
    <div class="col-xs-12 ">
        <!-- Form for Adding New Article -->
        <%= form_for @article do |f| %>
        <div class="form-group mb-2 ">
            <div class="form-label col-sm-2 mb-2">
                <%= f.label :title %>
            </div>
            <div class="col-sm-8">
                <%= f.text_field :title, class: "form-control", placeholder: "Title of Article", autofocus: true %>
            </div>
        </div>

        <div class="form-group mb-2 ">
            <div class="form-label col-sm-2 mb-2">
                <%= f.label :description %>
            </div>
            <div class="col-sm-8">
                <%= f.text_area :description, class: "form-control",rows: 6, placeholder: "Description of Article", autofocus: true %>
            </div>
        </div>
        <div class="form-group mb-2">
            <div class="col-sm-10 mb-2">
                    <%= f.submit class: "btn btn-success " %>
            </div>
        </div>
        <% end %>
        <div class="col-xs-4 col-xs-offset-4">
            [ <%= link_to "Cancel request and return to listing Articles", articles_path %> ] 
        </div>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center">Edit Existing Article</h1>

<!-- Call _form Partial -->
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center" >Listing All Article</h1>
<p>
<%= link_to "Create New Article", new_article_path %>
</p>

<div class="text-center">
    <%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer)  %> 
</div>

<%= render 'article', obj: @articles %>

<div class="text-center">
    <div class="m-auto">
    <%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer)%> 
    </div>
</div>

app/views/articles/new.html.erb
<h1 class="text-center">Create an article</h1>

<!-- Call _form Partial -->
<%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="text-center">Title: <%= @article.title %></h1>

<% if @article.user%>
<div class="text-center">
    <ul class="listing">
        <div class="row">
            <div class="col-md-4 col-md-offset-4 p-3 m-auto">
                <div class="card">
                    <div class="card-body">
                    <li>Created By:</li>
                        <li> <%= link_to gravatar_for(@article.user), user_path(@article.user) %> </li>
                        <li class="article-title">
                            <%= link_to @article.user.username, user_path(@article.user)  %> 
                        </li>
                    </div>
                </div>
                <!-- <li><small></small></li> -->
            </div>
        </div>
    </ul>
</div>
<% end %>



<div class="col-xs-8 col-xs-offset-2 py-4">
    <div class="card p-2 border-0 bg-card">
        <div class="card-body">
            <h4>
                <strong >Description:</strong>
                
                <%= simple_format(@article.description) %>
            </h4>
            <div class="article-actions">
                <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
                <%= link_to "Edit Article", edit_article_path(@article), class: "btn btn-sm btn-primary" %> 

                <%= button_to "Delete Article", article_path(@article), method: :delete, data: {confirm: "are you sure you want to delete the article?"}, class: "btn btn-sm btn-danger"  %>
                <% end %>
                <%= link_to "View all Articles", articles_path, class: "btn btn-sm btn-success" %> 
            </div> 
        </div>
    </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mb-3">
    Listing All Categories
</h1>

<div class="text-center">
    <div class="m-auto">
    <%= will_paginate(@categories, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer)%> 
    </div>
</div>

<div class="text-center mt-3">
    <% @categories.each do |category| %>
    <ul class="listing ">
        <div class="row">
            <div class=" col-md-4 col-md-offset-4 p-3 m-auto">
                <div class="card p-2 border-0 bg-card">
                    <div class="card-body">
                        <div class="article-title">
                            <%= link_to "#{category.name}", category_path(category) %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </ul>

    <% end %> 
</div>


<div class="text-center">
    <div class="m-auto">
    <%= will_paginate(@categories, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer)%> 
    </div>
</div>

app/views/categories/new.html.erb
<h1 class="text-center"> Create new category </h1>

<%= render 'shared/errors', obj: @category %>



<!-- Form for Adding New Article -->
<%= form_for @category do |f| %>
<div class="form-group mb-2 ">
    <div class="form-label col-sm-2 mb-2">
        <%= f.label :name %>
    </div>
    <div class="col-sm-8">
        <%= f.text_field :name, class: "form-control", placeholder: "category name", autofocus: true %>
    </div>
</div>

<div class="form-group mb-2">
    <div class="col-sm-10 mb-2">
            <%= f.submit class: "btn btn-success " %>
    </div>
</div>
<% end %>
<div class="col-xs-4 col-xs-offset-4">
    [ <%= link_to "Cancel request and return to listing Articles", articles_path %> ] 
</div>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer text-center mt-3 py-2 ">
        
            <small>
                Copyright &copy; Mazen Abo Elanin
            </small>
            <nav>
                <ul>
                    <li>
                        <%= link_to "About", about_path %>
                    </li>
                </ul>
            </nav>
        </div>
    </footer>

app/views/layouts/_messages.html.erb
<!-- Displaying Msg when article Created -->
<div class="container">

    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <% flash.each do |name, msg| %>
            <div class='alert alert-<%="#{name}" %>  alert-dismissible fade show'role="alert">
                <strong> <%= msg %> </strong>
            <button type="button" class='close btn btn-outline-<%="#{name}"%> btn-sm' data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3 ">
  <div class="container-fluid">
    <!--<a class="navbar-brand" id="logo" href="#">Alpha Blog</a> -->
    <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item">
          <!--<a class="nav-link" aria-current="page" href="#">Home</a>-->
          <%= link_to "Articles", articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, class: "nav-link" %>
        </li>
        <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Actions
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
            <!--<a class="dropdown-item" href="#">Action</a>-->
            <%= link_to "New Article", new_article_path, class: "dropdown-item" %>
            </li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>

        </li>
        <% end %>
                <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
            <%= link_to "All Categories ", categories_path, class: "dropdown-item" %>
            </li>
            <% Category.all.each do |category| %>
              <li><%= link_to "#{category.name}", category_path(category), class: "dropdown-item" %> </li>
            <% end %>
            
            <% if logged_in? and current_user.admin? %>
            <li><hr class="dropdown-divider"></li>
            <li> <%= link_to "Create New Category", new_category_path, class: "dropdown-item" %> </li>
            <% end %>
          </ul>

        </li>
      </ul>

      <ul class="navbar-nav mb-2 mb-lg-0 ms-auto">
      <% if logged_in?%>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Your Profile <%= "Admin" if current_user.admin? %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
            </li>
            <li><%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>

        </li>
        <li class="nav-item" style="background-color: transparent">
          <%= button_to "log out", logout_path, method: :delete %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "Login", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Signup", signup_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- Navbar -->
    <%= render 'layouts/navbar' %>
    <!-- Call flash messages partial -->
    <%= render 'layouts/messages' %>
    

  <div class="container">
   <%= yield %>
  </div>
  <!-- Footer -->
  <%= render 'layouts/footer' %>
  <!-- Display Debug when development-->
  <%= debug(params) if Rails.env.development? %>
   




  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>

<!-- Link -->
<%= link_to 'Home',  root_path %>

app/views/pages/home.html.erb
<div class="jumbotron p-5 bg-light rounded-3 text-center d-flex align-items-center">
    <div class="header-content m-auto" >
        <h1 class="display-5 fw-bold">Alpha Blog</h1>
        <!-- Link -->
        <%= link_to "Sign up", signup_path , class: "btn btn-primary btn-lg btn-xlarge " %>
    </div>

</div>

app/views/shared/_errors.html.erb
<!-- Displaying Errors -->
<% if obj.errors.any? %>
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="card border-danger p-2 my-3">
            <div class="card-body">
                <h2 class="card-title">
                    <% pluralize(obj.errors.count, "error") %> 
                    prohibited this article from being saved:
                </h2>
                <div class="card-text">
                    <ul>
                        <% obj.errors.full_messages.each do |msg| %>
                        <li> <%= msg %> </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/users/_form.html.erb
<!-- Displaying Erros -->
<% if @user.errors.any? %>
<h2>User Not created because of the Following errors</h2>
<ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
</ul>
<% end %>

<div class="row ">
    <div class="col-xs-12 ">
        <!-- Form for Adding New Article -->
        <%= form_for @user do |f| %>
        <div class="form-group mb-2 ">
            <div class="form-label col-sm-2 mb-2">
                <%= f.label :username %>
            </div>
            <div class="col-sm-8">
                <%= f.text_field :username, class: "form-control", placeholder: "Username", autofocus: true %>
            </div>
        </div>

        <div class="form-group mb-2 ">
            <div class="form-label col-sm-2 mb-2">
                <%= f.label :email %>
            </div>
            <div class="col-sm-8">
                <%= f.email_field :email, class: "form-control", placeholder: "Email" %>
            </div>
        </div>

        <div class="form-group mb-2 ">
            <div class="form-label col-sm-2 mb-2">
                <%= f.label :password %>
            </div>
            <div class="col-sm-8">
                <%= f.password_field :password, class: "form-control", placeholder: "Password"%>
            </div>
        </div>
        <div class="form-group mb-2">
            <div class="col-sm-10 mb-2">
                    <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-success ") %>
            </div>
        </div>
        <% end %>
        <div class="col-xs-4 col-xs-offset-4">
            [ <%= link_to "Cancel request and return to listing Articles", articles_path %> ] 
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center">Edit your account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center">All Alpha Bloggers</h1>


<div class="text-center">
<%= will_paginate(@users, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer)  %> 
<% @users.each do |user| %>
    <ul class="listing mt-3">
        <div class="row">
            <div class=" col-md-4 col-md-offset-4 p-3 m-auto">
                <div class="card p-2 border-0 bg-card">
                    <div class="card-body">
                        <li> <%= link_to gravatar_for(user), user_path(user) %> </li>
                        <li class="article-title">
                            <%= link_to user.username, user_path(user)  %> 
                        </li>
                        <!-- <li><small></small></li> -->
                        <% if logged_in? and current_user.admin? %>
                        <li> <%= button_to "Delete this user", user_path(user), method: :delete, data: {confirm: "are you sure to delete user and their article?"} %> </li>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </ul>

<% end %> 
</div>

app/views/users/new.html.erb
<h1 class="text-center">Sign Up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center">Welcome <%= @user.username %> </h1>

<div class="row mb-3">
    <div class="col-md-4 col-md-offset-4 text-center m-auto">
        <%= gravatar_for @user, size: 150 %> 
    </div>
</div>

<h4 class="text-center"><%= @user.username %>'s articles</h4>

<div class="text-center">
    <%= will_paginate(@user_articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer)  %> 
</div>
<%= render 'articles/article', obj: @user_articles %>


<div class="text-center">
    <%= will_paginate(@user_articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer)  %> 
</div>